// Export Module
const ExportManager = {
    exportPDF(semesters, cgpaResult) {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();

        // Title
        doc.setFontSize(18);
        doc.setFont('helvetica', 'bold');
        doc.text('SGPA & CGPA Report', pageWidth / 2, 20, { align: 'center' });

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(100);
        doc.text('KTU B.Tech Grade Point Average Calculator', pageWidth / 2, 27, { align: 'center' });
        doc.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth / 2, 33, { align: 'center' });

        let yPos = 45;

        semesters.forEach(sem => {
            const sgpaResult = Calculator.calculateSGPA(sem.subjects);

            if (yPos > 240) {
                doc.addPage();
                yPos = 20;
            }

            doc.setFontSize(13);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(0);
            doc.text(`Semester ${sem.semester}`, 14, yPos);

            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(67, 97, 238);
            doc.text(`SGPA: ${sgpaResult.sgpa.toFixed(2)}  |  Credits: ${sgpaResult.totalCredits}`, pageWidth - 14, yPos, { align: 'right' });

            yPos += 6;

            const tableData = sem.subjects.map(sub => [
                sub.name || '-',
                sub.code || '-',
                sub.grade || '-',
                sub.credits || '-',
                GRADE_POINTS[sub.grade] !== undefined ? GRADE_POINTS[sub.grade] : '-'
            ]);

            doc.autoTable({
                startY: yPos,
                head: [['Course Name', 'Code', 'Grade', 'Credits', 'Grade Point']],
                body: tableData,
                theme: 'grid',
                headStyles: {
                    fillColor: [67, 97, 238],
                    fontSize: 8,
                    fontStyle: 'bold'
                },
                bodyStyles: { fontSize: 8 },
                columnStyles: {
                    0: { cellWidth: 'auto' },
                    1: { cellWidth: 25 },
                    2: { cellWidth: 20 },
                    3: { cellWidth: 20 },
                    4: { cellWidth: 25 }
                },
                margin: { left: 14, right: 14 }
            });

            yPos = doc.lastAutoTable.finalY + 16;
        });

        // CGPA Summary
        if (yPos > 230) {
            doc.addPage();
            yPos = 20;
        }

        doc.setDrawColor(67, 97, 238);
        doc.setFillColor(240, 244, 255);
        doc.roundedRect(14, yPos, pageWidth - 28, 40, 3, 3, 'FD');

        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0);
        doc.text('Cumulative Grade Point Average (CGPA)', pageWidth / 2, yPos + 10, { align: 'center' });

        doc.setFontSize(24);
        doc.setTextColor(67, 97, 238);
        doc.text(cgpaResult.cgpa.toFixed(2), pageWidth / 2, yPos + 24, { align: 'center' });

        doc.setFontSize(9);
        doc.setTextColor(100);
        doc.text(
            `Total Credits: ${cgpaResult.totalCredits}  |  Percentage: ${cgpaResult.percentage.toFixed(2)}%  |  ${cgpaResult.classification}`,
            pageWidth / 2, yPos + 33, { align: 'center' }
        );

        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(
                'Generated by GPA Calculator | Developed by Amal Dev T S',
                pageWidth / 2,
                doc.internal.pageSize.getHeight() - 10,
                { align: 'center' }
            );
        }

        doc.save('SGPA_CGPA_Report.pdf');
    },

    exportExcel(semesters, cgpaResult) {
        const wb = XLSX.utils.book_new();

        semesters.forEach(sem => {
            const sgpaResult = Calculator.calculateSGPA(sem.subjects);
            const data = [
                ['Course Name', 'Code', 'Grade', 'Credits', 'Grade Point'],
                ...sem.subjects.map(sub => [
                    sub.name || '',
                    sub.code || '',
                    sub.grade || '',
                    sub.credits || 0,
                    GRADE_POINTS[sub.grade] !== undefined ? GRADE_POINTS[sub.grade] : ''
                ]),
                [],
                ['', '', 'Total Credits', sgpaResult.totalCredits, ''],
                ['', '', 'SGPA', sgpaResult.sgpa.toFixed(2), '']
            ];

            const ws = XLSX.utils.aoa_to_sheet(data);
            ws['!cols'] = [
                { wch: 40 }, { wch: 12 }, { wch: 10 }, { wch: 10 }, { wch: 12 }
            ];
            XLSX.utils.book_append_sheet(wb, ws, `Semester ${sem.semester}`);
        });

        const summaryData = [
            ['SGPA & CGPA Summary'],
            [],
            ['Semester', 'SGPA', 'Credits'],
            ...semesters.map(sem => {
                const r = Calculator.calculateSGPA(sem.subjects);
                return [`Semester ${sem.semester}`, r.sgpa.toFixed(2), r.totalCredits];
            }),
            [],
            ['CGPA', cgpaResult.cgpa.toFixed(2), cgpaResult.totalCredits],
            ['Equivalent Percentage', `${cgpaResult.percentage.toFixed(2)}%`, ''],
            ['Classification', cgpaResult.classification, ''],
            [],
            ['Generated by GPA Calculator | Developed by Amal Dev T S']
        ];

        const summaryWs = XLSX.utils.aoa_to_sheet(summaryData);
        summaryWs['!cols'] = [{ wch: 25 }, { wch: 15 }, { wch: 12 }];
        XLSX.utils.book_append_sheet(wb, summaryWs, 'Summary');

        XLSX.writeFile(wb, 'SGPA_CGPA_Report.xlsx');
    }
};